# This config controls the live site. 

title: FIXME Site Title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  FIXME Project Description
baseurl: "/CMCS-DSG-DSS-Certification"
url: ""
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# theme: just-the-docs
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
#   - jekyll-remote-theme
#   # - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
