# This config is used with 'make preview', or when being viewed locally under Docker.
# It will not affect the live site.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile

# Note: The footer_content option is deprecated and will be removed in a future major release. 
# Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: >
  This site is in the public domain; see <a href='LICENSE/'>the license</a> for more information.

# Footer "Edit this page on GitHub" link text
gh_edit_link: true 
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/CMSgov/CMCS-DSG-DSS-Certification"
gh_edit_branch: "main"
gh_edit_view_mode: "tree" 

# Footer last edited timestamp
# last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
# last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

