blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: github.com/CMSgov/CMCS-DSG-DSS-Certification/issues/new?template=issue_template.md&assignees=naretakis&labels=&title=&milestone=&projects=naretakis%2FCMCS-DSG-DSS-Certification%2F1
    about: Please ask and answer questions here.
